# Generated by Django 4.1.5 on 2023-01-19 22:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/user.png', upload_to=users.models.CustomUser.image_upload_to, verbose_name='Image'),
        ),
    ]
