# Generated by Django 4.1.5 on 2023-01-14 09:38

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0004_alter_category_published_alter_post_publish_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 9, 38, 25, 591802, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 9, 38, 25, 592336, tzinfo=datetime.timezone.utc)),
        ),
    ]
