# Generated by Django 4.1.5 on 2023-01-19 20:17

import blog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_author_alter_category_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=blog.models.Category.image_upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=blog.models.Post.image_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 20, 17, 1, 112711, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 20, 17, 1, 113470, tzinfo=datetime.timezone.utc)),
        ),
    ]
