# Generated by Django 4.1.5 on 2023-01-25 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_published_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 20, 14, 20, 876959, tzinfo=datetime.timezone.utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 20, 14, 20, 877701, tzinfo=datetime.timezone.utc)),
        ),
    ]
